### PR TITLE
erdantic: rename {typing, pydantic, dataclasses}

### PR DESCRIPTION
**Pull request by adsharma**
This avoids namespace conflict and makes the cli usable without
forcing me to setup.py install for testing changes.

### CODE REVIEW

**Comment by jayqi** [comment]
Hi @adsharma. It's not clear to me what the problem you are encountering is. If you're doing development and testing changes, it's generally recommended to install the package so that you are testing the same thing as what a user would get if they installed from PyPI. If you are able to share additional details about the problems that you're encountering, I might be able to offer some suggestions. 

I'm most likely not going to accept this change to rename all of the modules in this package, unless you're able to explain more clearly why you think this is necessary.

**Comment by adsharma** [comment]
Here's the problem I was encountering:

```
python3 erdantic/cli.py 
Traceback (most recent call last):
  File "erdantic/cli.py", line 3, in <module>
    from typing import List, Optional
  File "/home/arun/src/e1/erdantic/typing.py", line 2, in <module>
    from typing import Any, List, Type, Union
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (/home/arun/src/e1/erdantic/typing.py)
```

Having files named like builtin modules is causing you other bad code such as:

```
import pydantic
import pydantic.fields
```

and the two instances of F401 this PR removes.

Granted everything needs to work after installation, which it does after this PR as well. But being able to work on stuff without having to install is generally good hygiene.

**Comment by adsharma** [comment]
More descriptive explanation here:

http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap

**Comment by jayqi** [comment]
I am still not quite sure how you end up in a situation where your Python path is inside the erdantic directory in that way. `erdantic` _is_ a package and not a series of scripts. I don't think `python3 erdantic/cli.py` should be an expected entrypoint for any functionality of the package. You are expected either to import functions from the modules, or you are expected to use the CLI. You can try `python3 -m erdantic` instead to access the CLI.

**Comment by adsharma** [comment]
Well, I've pointed out the consequences of not so great naming choices you've made. I'll make a couple of more commits and maintain them in my fork. Thank you for writing the tool.

My python path was empty and you can try this yourself:

```
mkdir /tmp/test
cat /tmp/test/typing.py
from typing import Any

print("hello")
python3 /tmp/test/typing.py
```

**Comment by jayqi** [comment]
@adsharma  I appreciate that you took the time to explanation the shadowing issue, and I can in fact reproduce your error if I run `python3 erdantic/cli.py`. 

My response is that `python3 erdantic/cli.py` is not a supported way of using erdantic. erdantic is designed as a package, so invoking any of the submodules in the manner of `python3 erdantic/*.py` is not supported. As an alternative, I suggest accessing the CLI through `python3 -m erdantic`. I am able to use the CLI that way without having the package installed.

```bash
❯ pip uninstall erdantic
WARNING: Skipping erdantic as it is not installed.
❯ python3 -m erdantic --help
Usage: python -m erdantic [OPTIONS] MODELS...

  Draw entity relationship diagrams (ERDs) for Python data model classes.
  ...
```

**Comment by adsharma** [comment]
https://github.com/adsharma/erdantic/commit/713b6745042bdc983a3571533dedb1256c6adcf7

Shows how I prefer to invoke it (make cli.py executable). With this change, I was able to get faster edit-compile-debug cycles and was able to finish the actual work sooner.

**Pull request closed without merging**
