### PR TITLE
feat: Add optional modality and cardinality overrides to `Edge`

### PR DESCRIPTION
**Pull request by ion-elgreco**
This adds the possibility of overriding the modality and cardinality of each edge. Closes https://github.com/drivendataorg/erdantic/issues/88

It would also nice if we can backport this to the release with pydantic v1

### CODE REVIEW

**Comment by ion-elgreco** [comment]
@jayqi  @pjbull

**Comment by ion-elgreco** [comment]
@jayqi @pjbull is this repo still maintained?

**Comment by jayqi** [comment]
Hi @ion-elgreco,

Sorry for the delay in responding your issues and this PR. This project is maintained, but since it's a small project with a small team, we can be slow to respond. Thanks for following up.

I think the change you would like to make points to a larger change that I've been thinking about with regards to erdantic's architecture, which is to generally make some of these fields on erdantic's data objects to be attributes rather than properties. That would allow a user to more easily edit anything. 

I'm hesitant about accepting this PR—since it feels like a bit of a messy and confusing new API surface because the existing API that doesn't really lend itself to this idea very well. However, I am open to it, since this mainly affects internals from the perspective of most users, and the new design I have in mind would be a large breaking change to the API of the internal data objects either way. Is this something that would be a big help to you if it were released? 

With that in mind, here are some preferences that I have regarding these changes. I am open to being convinced otherwise on both:

- Use Enums instead of string literals.
- Rather than "one" and "zero", I think modality would be more clear if the values are "nullable" and "not null".

**Comment by ion-elgreco** [comment]
> 
Having it as attributes sounds good to me. The new change in the API you propose would be useful. Currently the way these relations are inferred don't make much sense, so there needs to be a way to control them if needed.

Changing string literals to Enums is fine by me.

I rather prefer one, zero since you read these relations as one-to-many or zero-to-one etc.

**Comment by ion-elgreco** [comment]
Closing since there is no reception

**Pull request closed without merging**
